ALTER TYPE "AccessType" ADD VALUE IF NOT EXISTS 'SANKHYA';

ALTER TABLE "AccessItem"
ADD COLUMN IF NOT EXISTS "credentialId" TEXT,
ADD COLUMN IF NOT EXISTS "credentialSecret" TEXT,
ADD COLUMN IF NOT EXISTS "credentialToken" TEXT;
